### ISSUE TITLE
Service Loading problem, Unspecified Modules in Maven

### ISSUE THREAD

**Issue by ItsBlockFighter** [FairyProject/fairy#13]
This error has occurred in other Services such as `SerializerFactory`
```
[15:54:18 INFO]: [Fairy] Enabling Fairy v0.5b59
[15:54:18 INFO]: ModuleService onPreInitialize
[15:54:18 INFO]: Registering module bukkit-xseries...
[15:54:20 INFO]: Registering module core-command...
[15:54:20 WARN]: java.lang.IllegalStateException: An exception has been thrown while scanning ContainerObject for dev.duaservices.bravo.fairy.command.CommandService
[15:54:20 WARN]:        at io.fairyproject.container.ContainerContext$ClassPathScanner.scan(ContainerContext.java:515)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService.registerByPath(ModuleService.java:265)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService.registerByName(ModuleService.java:154)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService.registerByPath(ModuleService.java:199)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService.registerByPath(ModuleService.java:166)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService$1.lambda$null$1(ModuleService.java:78)
[15:54:20 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService$1.lambda$onPluginInitial$2(ModuleService.java:75)
[15:54:20 WARN]:        at io.fairyproject.util.PreProcessBatch.flushQueue(PreProcessBatch.java:43)
[15:54:20 WARN]:        at io.fairyproject.module.ModuleService.onPostInitialize(ModuleService.java:136)
[15:54:20 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:54:20 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:54:20 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:54:20 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[15:54:20 WARN]:        at io.fairyproject.container.object.BaseContainerObject.call(BaseContainerObject.java:225)
[15:54:20 WARN]:        at io.fairyproject.container.object.BaseContainerObject.lifeCycle(BaseContainerObject.java:204)
[15:54:20 WARN]:        at io.fairyproject.container.ContainerContext.lifeCycle(ContainerContext.java:379)
[15:54:20 WARN]:        at io.fairyproject.container.ContainerContext$ClassPathScanner.scan(ContainerContext.java:635)
[15:54:20 WARN]:        at io.fairyproject.container.ContainerContext.init(ContainerContext.java:116)
[15:54:20 WARN]:        at io.fairyproject.FairyPlatform.enable(FairyPlatform.java:77)
[15:54:20 WARN]:        at io.fairyproject.bukkit.FairyBukkitPlatform.enable(FairyBukkitPlatform.java:96)
[15:54:20 WARN]:        at io.fairyproject.bukkit.plugin.FairyInternalPlugin.onEnable(FairyInternalPlugin.java:17)
[15:54:20 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:54:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[15:54:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[15:54:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[15:54:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[15:54:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[15:54:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[15:54:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[15:54:20 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[15:54:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[15:54:20 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:54:20 WARN]: Caused by: java.lang.NullPointerException: The type dev.duaservices.bravo.fairy.command.CommandService doesn't have @Service annotation! []
[15:54:20 WARN]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
[15:54:20 WARN]:        at io.fairyproject.container.ContainerContext$ClassPathScanner.scan(ContainerContext.java:500)
[15:54:20 WARN]:        ... 32 more
[15:54:20 ERROR]: Unable to find dependency module core-command for bukkit-command
```

In the Maven Repository, there are some modules that don't have a version (unspecified) and the Framework wants to download them first. `core-config`

**Comment by LeeGodSRC** [comment]
Hey, your fairy version seems to be out-dated, try installing Fairy 0.5.1b12 (delete fairy.jar and let it re-download should does the job)
And make sure your modules are up-to-date

**Comment by LeeGodSRC** [comment]
Nevermind something seems to be messed up

**Comment by LeeGodSRC** [comment]
This should be fixed in latest merged PR, please delete fairy.jar and let it re-download
