### ISSUE TITLE
Fix Java 22 Support

### ISSUE THREAD

**Issue by LeeGodSRC** [FairyProject/fairy#151]
```
[19:47:48] [Server thread/ERROR]: Error occurred while enabling fairy-lib-plugin v0.7.4b1-SNAPSHOT (Is it up to date?)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class io.fairyproject.reflect.Reflect
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.fairyproject.util.exceptionally.ThrowingRunnable.lambda$sneaky$1(ThrowingRunnable.java:39) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.load(ContainerNodeLoader.java:85) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.ContainerContext.loadContainerNode(ContainerContext.java:140) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.RootNodeLoader.loadNode(RootNodeLoader.java:55) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.RootNodeLoader.load(RootNodeLoader.java:49) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.ContainerContext.init(ContainerContext.java:98) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.FairyPlatform.enable(FairyPlatform.java:85) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.bukkit.FairyBukkitPlatform.enable(FairyBukkitPlatform.java:98) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.library.bootstrap.platform.AbstractPlatformBootstrap.enable(AbstractPlatformBootstrap.java:74) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.library.bootstrap.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:89) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-399]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-399]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-399]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-399]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[paper-1.20.4.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-399]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.fairyproject.reflect.Reflect
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.lambda$injectAutowiredField$2(AutowiredAnnotationProcessor.java:114) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214) ~[?:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.injectAutowiredField(AutowiredAnnotationProcessor.java:111) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.processPreInitialization(AutowiredAnnotationProcessor.java:79) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.lambda$callPreInitProcessors$0(ContainerNodeLoader.java:134) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.callPreInitProcessors(ContainerNodeLoader.java:136) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.lambda$directlyCompose$10(ContainerNodeLoader.java:275) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:[482](https://mclo.gs/chL4jyS#L482)) ~[?:?]
	at io.fairyproject.util.thread.BlockingThreadAwaitQueue.await(BlockingThreadAwaitQueue.java:46) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.load(ContainerNodeLoader.java:84) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Unsafe not found [in thread "Server thread"]
	at io.fairyproject.reflect.Reflect.<clinit>(Reflect.java:58) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.lambda$injectAutowiredField$2(AutowiredAnnotationProcessor.java:114) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214) ~[?:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.injectAutowiredField(AutowiredAnnotationProcessor.java:111) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor$NodeContext.injectStaticFields(AutowiredAnnotationProcessor.java:131) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.processNodePreInitialization(AutowiredAnnotationProcessor.java:103) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.callNodePreInitProcessors(ContainerNodeLoader.java:91) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:819) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:803) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2227) ~[?:?]
	at io.fairyproject.container.node.loader.ContainerNodeLoader.load(ContainerNodeLoader.java:78) ~[fairy-lib-plugin-0.7.4b1-SNAPSHOT-all.jar:?]
	... 20 more
```

**Comment by LeeGodSRC** [comment]
This fixed
