### ISSUE TITLE
Outdated Command Documentation

### ISSUE THREAD

**Issue by maurxce** [FairyProject/fairy#170]
URL: https://docs.fairyproject.io/modules/command/

## Arguments
When using arguments, as the documetation suggests:
```java
@Arg("name") 
private String name;
```
I got the following error:
```
[18:51:54] [Server thread/INFO]: [ERROR] !-------------------!
[18:51:54] [Server thread/INFO]: [ERROR] An error was reported with Fairy container system!!
[18:51:54] [Server thread/INFO]: [ERROR] Node: Opdrachten
[18:51:54] [Server thread/INFO]: [ERROR] Component: md.schorn.opdrachten.command.ExampleCommand
[18:51:54] [Server thread/INFO]: [ERROR]  
[18:51:54] [Server thread/INFO]: [ERROR] Messages:
[18:51:54] [Server thread/INFO]: [ERROR] >    initializing
[18:51:54] [Server thread/INFO]: [ERROR]  
[18:51:54] [Server thread/INFO]: [ERROR] The error stacktrace: 
[18:51:54] [Server thread/ERROR]: [Fairy] java.lang.IllegalArgumentException: Field private java.lang.String md.schorn.opdrachten.command.ExampleCommand.name marked @Arg but not using type class md.schorn.opdrachten.fairy.command.argument.ArgProperty
```

## Command Presence
The example for sub-commands is using a `CommandPresence` annotation:
```java
@CommandPresence(DefaultPresenceProvider.class)
```
but when Implementing this, I got the following error:
```
[14:10:17 ERROR]: Command exception: /opdrachten
java.lang.NullPointerException: Cannot invoke "md.schorn.opdrachten.fairy.command.PresenceProvider.sendMessage(md.schorn.opdrachten.fairy.command.CommandContext, md.schorn.opdrachten.fairy.command.MessageType, String[])" because "this.presenceProvider" is null
        at Opdrachten-0.0.46-all.jar/md.schorn.opdrachten.fairy.command.CommandContext.sendMessage(CommandContext.java:85) ~[Opdrachten-0.0.46-all.jar:?]
        at Opdrachten-0.0.46-all.jar/md.schorn.opdrachten.fairy.command.BaseCommand.onError(BaseCommand.java:138) ~[Opdrachten-0.0.46-all.jar:?]
        at Opdrachten-0.0.46-all.jar/md.schorn.opdrachten.fairy.bukkit.command.BukkitCommandExecutor.execute(BukkitCommandExecutor.java:50) ~[Opdrachten-0.0.46-all.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LeeGodSRC** [comment]
Hey @maurxce ! we've just updated all the command documentation! thanks for reporting.
