### ISSUE TITLE
dependency injection across plugins

### ISSUE THREAD

**Issue by QwQ-dev** [FairyProject/fairy#175]
so like this:

me.qwqdev.library.A, is plugin A's class
me.qwqdev.library.B, is plugin B's class

how can I make me.qwqdev.library.A be injected into B plugin? (use fairy lib plugin)

i try add depends but not work:

```
Caused by: java.lang.IllegalArgumentException: Couldn't find container object me.qwqdev.library.annotation.service.AnnotationProcessingService! may not be null
	at fairy-lib-plugin.jar//io.fairyproject.util.ConditionUtils.notNull(ConditionUtils.java:41)
	at fairy-lib-plugin.jar//io.fairyproject.container.object.resolver.ContainerObjectResolverImpl.resolveInstance(ContainerObjectResolverImpl.java:60)
	at fairy-lib-plugin.jar//io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.injectAutowiredField(AutowiredAnnotationProcessor.java:107)
	at fairy-lib-plugin.jar//io.fairyproject.container.processor.injection.AutowiredAnnotationProcessor.processPreInitialization(AutowiredAnnotationProcessor.java:77)
	... 28 more
```

**Comment by LeeGodSRC** [comment]
Do you have plugin B depend on plugin A in bukkit plugin.yml?

**Comment by QwQ-dev** [comment]
![image](https://github.com/user-attachments/assets/482c6108-a488-472b-a5ff-275c2047a058)


i solved it~ and i love fairy framework
