### ISSUE TITLE
NoSuchFileException error on compiling unit test

### ISSUE THREAD

**Issue by LeeGodSRC** [FairyProject/fairy#23]
```
Caused by: java.nio.file.NoSuchFileException: /mnt/disk/ideaProjects/_imanity/untitled/build/classes/java/test/MODULE.class
	at io.fairyproject.gradle.FairyTestTask.afterTestClasses(FairyTestTask.java:39)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	... 118 more
```

platform: APP
modules: discord, command

This error doesn't affect the actual file compiled but unit test is not working

**Comment by LeeGodSRC** [comment]
This issue still remains in gradle plugin 1.0.0b6

**Comment by LeeGodSRC** [comment]
fixed
