### ISSUE TITLE
RedisService problem

### ISSUE THREAD

**Issue by ItsBlockFighter** [FairyProject/fairy#3]
When I turn on Redis I get the following error:
```
[21:15:20 WARN]: java.lang.reflect.InvocationTargetException
[21:15:20 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:15:20 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:15:20 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:15:20 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[21:15:20 WARN]:        at org.fairy.bean.details.GenericBeanDetails.call(GenericBeanDetails.java:210)
[21:15:20 WARN]:        at org.fairy.bean.BeanContext.call(BeanContext.java:551)
[21:15:20 WARN]:        at org.fairy.bean.BeanContext.scanClasses(BeanContext.java:507)
[21:15:20 WARN]:        at org.fairy.bean.BeanContext.init(BeanContext.java:97)
[21:15:20 WARN]:        at org.fairy.FairyBootstrap.enable(FairyBootstrap.java:81)
[21:15:20 WARN]:        at org.fairy.bukkit.FairyBukkitPlatform.onEnable(FairyBukkitPlatform.java:80)
[21:15:20 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[21:15:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:15:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[21:15:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[21:15:20 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[21:15:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[21:15:20 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:20 WARN]: Caused by: java.lang.NoSuchMethodError: org.redisson.codec.JsonJacksonCodec.<init>(Lcom/fasterxml/jackson/databind/ObjectMapper;)V
[21:15:20 WARN]:        at org.fairy.redis.RedisService.preInit(RedisService.java:64)
[21:15:20 WARN]:        ... 18 more
[21:15:21 WARN]: java.lang.NullPointerException
[21:15:21 WARN]:        at org.fairy.redis.RedisService.getKeys(RedisService.java:85)
[21:15:21 WARN]:        at org.fairy.redis.server.thread.FetchThread.fetch(FetchThread.java:64)
[21:15:21 WARN]:        at org.fairy.redis.server.thread.FetchThread.run(FetchThread.java:50)
[21:15:21 WARN]: java.lang.reflect.InvocationTargetException
[21:15:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:15:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:15:21 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:15:21 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[21:15:21 WARN]:        at org.fairy.bean.details.GenericBeanDetails.call(GenericBeanDetails.java:210)
[21:15:21 WARN]:        at org.fairy.bean.BeanContext.call(BeanContext.java:551)
[21:15:21 WARN]:        at org.fairy.bean.BeanContext.scanClasses(BeanContext.java:543)
[21:15:21 WARN]:        at org.fairy.bean.BeanContext.init(BeanContext.java:97)
[21:15:21 WARN]:        at org.fairy.FairyBootstrap.enable(FairyBootstrap.java:81)
[21:15:21 WARN]:        at org.fairy.bukkit.FairyBukkitPlatform.onEnable(FairyBukkitPlatform.java:80)
[21:15:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[21:15:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:15:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[21:15:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[21:15:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[21:15:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[21:15:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:21 WARN]: Caused by: java.lang.NullPointerException
[21:15:21 WARN]:        at org.fairy.redis.subscription.RedisPubSub.<init>(RedisPubSub.java:42)
[21:15:21 WARN]:        at org.fairy.redis.message.MessageService.init(MessageService.java:77)
[21:15:21 WARN]:        ... 18 more
[21:15:21 WARN]: java.lang.NullPointerException
[21:15:21 WARN]:        at org.fairy.redis.RedisService.getMap(RedisService.java:81)
[21:15:21 WARN]:        at org.fairy.redis.server.thread.PushThread.push(PushThread.java:75)
[21:15:21 WARN]:        at org.fairy.redis.server.thread.PushThread.run(PushThread.java:49)

**Comment by LeeGodSRC** [comment]
Redis module is no longer a thing
