### ISSUE TITLE
@Cacheable Aspect compile error

### ISSUE THREAD

**Issue by LeeGodSRC** [FairyProject/fairy#37]
### Reproduce:
Enable CacheableAspect in core platform
Compile project that uses fairy with CacheableAspect enabled
The error appears and compile failed

### Extra Info:
The error only happens after shadowJar, which means the default build jar will not cause the error for some reason??

### Current Solution:
Removed `@Cacheable`

### Error:

```
---- AspectJ Properties ---
AspectJ Compiler 1.9.7 built on Thursday Jun 24, 2021 at 16:14:45 PDT
---- Dump Properties ---
Dump file: ajcore.20220223.153957.254.txt
Dump reason: org.aspectj.weaver.BCException
Dump on exception: true
Dump at exit condition: abort
---- Exception Information ---
---- System Properties ---
java.runtime.name=OpenJDK Runtime Environment
sun.boot.library.path=/usr/lib/jvm/java-8-openjdk/jre/lib/amd64
java.vm.version=25.292-b10
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=OpenJDK 64-Bit Server VM
file.encoding.pkg=sun.io
sun.java.launcher=SUN_STANDARD
user.country=TW
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/mnt/disk/ideaProjects/_fairy/main/test-plugin
java.runtime.version=1.8.0_292-b10
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk/jre/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

java.vm.specification.vendor=Oracle Corporation
user.variant=
os.name=Linux
sun.jnu.encoding=UTF-8
java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=5.10.84-1-MANJARO
user.home=/home/lee
user.timezone=Asia/Ho_Chi_Minh
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=/home/lee/.gradle/caches/modules-2/files-2.1/org.aspectj/aspectjtools/1.9.7/1eb5dbd0fe0fcf7b93b149127b0604c482f46aec/aspectjtools-1.9.7.jar
user.name=lee
java.vm.specification.version=1.8
sun.java.command=org.aspectj.tools.ajc.Main -argfile /mnt/disk/ideaProjects/_fairy/main/test-plugin/build/tmp/compileJava/ajc.options
java.home=/usr/lib/jvm/java-8-openjdk/jre
sun.arch.data.model=64
user.language=zh
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_292
java.ext.dirs=/usr/lib/jvm/java-8-openjdk/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/usr/lib/jvm/java-8-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk/jre/classes
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
sun.cpu.isalist=
---- Command Line ---
-argfile
/mnt/disk/ideaProjects/_fairy/main/test-plugin/build/tmp/compileJava/ajc.options
---- Full Classpath ---
Empty
---- Compiler Messages ---
abort ABORT -- (BCException) malformed org.aspectj.weaver.EffectiveSignature attribute (length:27)org.aspectj.weaver.BCException: Bad type signature (Lio/fairyproject/cache/CacheableAspect;)Ljava/lang/Runnable;
when batch building BuildConfig[null] #Files=0 AopXmls=#0

when batch building BuildConfig[null] #Files=0 AopXmls=#0

malformed org.aspectj.weaver.EffectiveSignature attribute (length:27)org.aspectj.weaver.BCException: Bad type signature (Lio/fairyproject/cache/CacheableAspect;)Ljava/lang/Runnable;
when batch building BuildConfig[null] #Files=0 AopXmls=#0

when batch building BuildConfig[null] #Files=0 AopXmls=#0

org.aspectj.weaver.BCException: malformed org.aspectj.weaver.EffectiveSignature attribute (length:27)org.aspectj.weaver.BCException: Bad type signature (Lio/fairyproject/cache/CacheableAspect;)Ljava/lang/Runnable;
when batch building BuildConfig[null] #Files=0 AopXmls=#0

when batch building BuildConfig[null] #Files=0 AopXmls=#0

	at org.aspectj.weaver.AjAttribute.read(AjAttribute.java:137)
	at org.aspectj.weaver.bcel.Utility.readAjAttributes(Utility.java:102)
	at org.aspectj.weaver.bcel.BcelMethod.unpackAjAttributes(BcelMethod.java:197)
	at org.aspectj.weaver.bcel.BcelMethod.<init>(BcelMethod.java:91)
	at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredMethods(BcelObjectType.java:290)
	at org.aspectj.weaver.ReferenceType.getDeclaredMethods(ReferenceType.java:870)
	at org.aspectj.weaver.ResolvedType.getDeclaredAdvice(ResolvedType.java:1028)
	at org.aspectj.weaver.ResolvedType.getDeclaredShadowMungers(ResolvedType.java:1068)
	at org.aspectj.weaver.ResolvedType.collectShadowMungers(ResolvedType.java:868)
	at org.aspectj.weaver.ResolvedType.collectCrosscuttingMembers(ResolvedType.java:794)
	at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:112)
	at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:67)
	at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:241)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:868)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:252)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:188)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:103)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:47)
	at org.aspectj.tools.ajc.Main.run(Main.java:372)
	at org.aspectj.tools.ajc.Main.runMain(Main.java:250)
	at org.aspectj.tools.ajc.Main.main(Main.java:84)
```

**Comment by LeeGodSRC** [comment]
aspectj feature has been fully removed since Fairy 0.6+
