### ISSUE TITLE
Storage module with mongo leads to collision

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#40]
Stack trace;

```
[04:57:53 INFO]: [Fairy] Enabling Fairy v0.5.1b12
[04:57:54 INFO]: Loaded Library mariadb-java-client v2.7.0
[04:57:54 INFO]: Loaded Library h2 v1.4.199
[04:57:54 INFO]: Loaded Library HikariCP v3.4.5
[04:57:54 INFO]: Loaded Library postgresql v9.4.1212
[04:57:54 INFO]: Loaded Library mysql-connector-java v8.0.22
[04:57:54 INFO]: Loaded Library byte-buddy v1.10.9
[04:57:54 INFO]: Loaded Library mysql-connector-java v8.0.22
[04:57:54 INFO]: Loaded Library mariadb-java-client v2.7.0
[04:57:54 INFO]: Loaded Library HikariCP v3.4.5
[04:57:54 INFO]: Loaded Library postgresql v9.4.1212
[04:57:54 INFO]: Loaded Library h2 v1.4.199
[04:57:54 INFO]: Loaded Library byte-buddy v1.10.9
[04:57:54 ERROR]: Something wrong will scanning component for dev.ghast.nftx.apeinvaders.arena.fairy.mysql.pojo.impl.UUIDObjectSerializer
java.lang.IllegalArgumentException: The Serializer for java.util.UUID already exists!
        at io.fairyproject.container.SerializerFactory$1.newInstance(SerializerFactory.java:72) ~[?:?]
        at io.fairyproject.container.ComponentRegistry.scanComponents(ComponentRegistry.java:87) ~[?:?]
        at io.fairyproject.container.scanner.ThreadedClassPathScanner.scanComponentAndInjection(ThreadedClassPathScanner.java:63) ~[?:?]
        at io.fairyproject.container.scanner.ThreadedClassPathScanner.lambda$directlyCompose$9(ThreadedClassPathScanner.java:126) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) [?:1.8.0_282]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) [?:1.8.0_282]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_282]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

Should be pretty self-explanatory

**Comment by terminalsin** [comment]
(Problem lies with java.lang.IllegalArgumentException: The Serializer for java.util.UUID already exists!)

**Comment by LeeGodSRC** [comment]
Do you have multiple plugins with fairy that has storage module in it?

**Comment by terminalsin** [comment]
Yes
