### ISSUE TITLE
[Critical] Multihreaded classpath scanner still deadlocks

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#59]
```
"Container Thread - 0@20350" daemon prio=5 tid=0x48 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Server thread@12064 to release lock on <0x5516> (a org.bukkit.plugin.SimplePluginManager)
	  at org.bukkit.plugin.SimplePluginManager.getPlugin(SimplePluginManager.java:451)
	  at co.aikar.timings.TimingsManager.getCommandTiming(TimingsManager.java:156)
	  at org.bukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:73)
	  at org.bukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:65)
	  at dev.ghast.nftx.apeinvaders.arena.fairy.bukkit.command.BukkitCommandListener.onCommandInitial(BukkitCommandListener.java:39)
```

```
"Server thread@12064" prio=7 tid=0x1c nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks Container Thread - 0@20350
	  at io.fairyproject.util.thread.BlockingThreadAwaitQueue.await(BlockingThreadAwaitQueue.java:57)
	  at io.fairyproject.container.scanner.ThreadedClassPathScanner.scanBlocking(ThreadedClassPathScanner.java:53)
	  at io.fairyproject.container.ContainerContext$1.onPluginEnable(ContainerContext.java:203)
	  at io.fairyproject.plugin.PluginManager.lambda$onPluginEnable$2(PluginManager.java:85)
	  at io.fairyproject.plugin.PluginManager$$Lambda$5367/0x0000000801e8f538.accept(Unknown Source:-1)
	  at java.lang.Iterable.forEach(Iterable.java:75)
	  at io.fairyproject.plugin.PluginManager.onPluginEnable(PluginManager.java:85)
	  - locked <0x5515> (a java.util.TreeSet)
```

**Comment by LeeGodSRC** [comment]
Do you have full thread dump? It's not suppose to have deadlock now unless other class is accessing the class in another thread

**Comment by LeeGodSRC** [comment]
Can someone test if this issue still occur in 0.6?

**Comment by LeeGodSRC** [comment]
Don't really think this is a case anymore
